version: "3"

volumes:
  static:

services:
  mysql:
    image: "mysql"
    environment:
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_USER: root
        MYSQL_PASSWORD: ''
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
     - ./dbs/:/var/lib/mysql
     - ./mysql/:/docker-entrypoint-initdb.d/
    restart: always
  web:
    environment:
      DJANGO_SETTINGS_MODULE: production_settings
    image: "docker.io/zaplon/gabinet_prod:latest"
    restart: always
    working_dir: /app/
    volumes:
      - static:/app/public/static/
    links:
      - mysql
    command: uwsgi --http 0.0.0.0:9001 --module docker_wsgi_configuration_module
#  elasticsearch:
#    image: elasticsearch
  wkhtmltopdf:
    image: michaelperrin/wkhtmltopdf:latest
  nginx:
    image: nginx
    networks:
      default:
        aliases:
          - gabinet
    depends_on:
      - web
    volumes:
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./nginx/sites-available/:/etc/nginx/sites-available/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public/media/:/media/
      - static:/static/
    ports:
      - "80:80"
      - "443:443"
  memcached:
    image: memcached